---
title: "Strings_and_factors"
author: "Shina Min"
date: "2023-10-22"
output: github_document
---


```{r setup, include = FALSE}
library(tidyverse)

library(p8105.datasets)
library(rvest)


knitr::opts_chunk$set(
  fig.width = .6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Strings and regex

```{r}
string_vec = c("my", "name", "is", "shina")

str_detect(string_vec, "shina")
str_replace(string_vec, "shina", "Shina")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun",
  "it will be fun, i think"
)

str_detect(string_vec, "^i think") # ^ is the beginning of the line that I am interested 

str_detect(string_vec, "i think$") # $ is the end of the line
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
)

str_detect(string_vec, "[Bb]ush")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]") # number first and a letter follows right after
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") # . is a special character in regular expressions that matches literally anything that might exist in a string

str_detect(string_vec, "7\\.11") # if I want to detect the dot specifically, I need to put two \\ in front of .
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
```


## Factors

```{r}
factor_vec = factor(c("male", "male", "female", "female"))

factor_vec

as.numeric(factor_vec) # converting my level to numeric values 
```

what happens if i relevel...

```{r}

factor_vec = fct_relevel(factor_vec, "male")

factor_vec

as.numeric(factor_vec)
```


## NSDUH

```{r}
url = "https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj =
  read_html(url) %>%
  html_table() %>%  
  first() %>%
  slice(-1) %>% # access specific rows in a data set (removing the first row)
  as_tibble() # converting to a tibble
```

```{r}
# I don't want the p value to float around
# age range (variety of ranges floating around)
# year

data_marj =
  table_marj %>%
  select(-contains("P Value")) %>% # -contains is to remove strings
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent"
  ) %>%
  separate(age_year, into = c("age", "year"), sep = "\\(") %>%
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$",""),
    percent = as.numeric(percent)
  ) %>%
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))

```


## NSDUH -- factors 

```{r}
data_marj %>%
  filter(age == "12-17") %>%
  mutate(State = fct_reorder(State, percent)) %>%
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

